; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[Monochrome]
accent=e5e7eb
accent-active=e5e7eb
accent-inactive=7a7c7d
banner=e5e7eb
border-active=e5e7eb
border-inactive=262626
header=e5e7eb
highlight=7a7c7d
main=18181b
notification=4687d6
notification-error=e22134
subtext=b2b2b2
text=FFFFFF